<?php
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.
PHP file generated by Adobe Muse CC 2018.1.0.386
*/
require_once('form_process.php');
$form = array(
	'subject' => 'Formulario del Equipo Enviado',
	'heading' => 'Nuevo Formulario Enviado',
	'success_redirect' => '/equipo/',
	'resources' => array(
		'checkbox_checked' => 'Checkeado',
		'checkbox_unchecked' => 'Uncheckeado',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Demasiados envíos recientes de esta IP',
		'failed_to_send_email' => 'Fallo al enviar email',
		'invalid_reCAPTCHA_private_key' => 'Clave privada reCAPTCHA inválida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada reCAPTCHA 2.0 inválida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta del servidor reCAPTCHA 2.0 inválida.',
		'invalid_field_type' => 'Tipo de campo desconocido \'%s\'.',
		'invalid_form_config' => 'El campo \'%s\' tiene una configuración inválida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'noreply@terracoin.io',
		'to' => 'support@terracoin.io'
	),
	'fields' => array(
		'name' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombre',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombre\' es necesario.'
			)
		),
		'email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Email\' es necesario.',
				'format' => 'El campo \'Email\' tiene un email inválido.'
			)
		),
		'message' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Mensaje',
			'required' => false,
			'errors' => array(
			)
		)
	)
);
process_form($form);
?>
