<?php
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => '团队表格提交',
	'heading' => '新表格提交',
	'success_redirect' => '/team/',
	'resources' => array(
		'checkbox_checked' => '已选中',
		'checkbox_unchecked' => '未选中',
		'submitted_from' => '从网站提交的表单: %s',
		'submitted_by' => '访客IP地址: %s',
		'too_many_submissions' => '来自此IP的最近提交的数量太多',
		'failed_to_send_email' => '无法发送电子邮件',
		'invalid_reCAPTCHA_private_key' => '无效的reCAPTCHA私钥。',
		'invalid_reCAPTCHA2_private_key' => '无效的reCAPTCHA 2.0私钥。',
		'invalid_reCAPTCHA2_server_response' => '无效的reCAPTCHA 2.0服务器响应。',
		'invalid_field_type' => '未知字段类型\'%s\'.',
		'invalid_form_config' => '字段\'%s\'配置无效。',
		'unknown_method' => '未知服务器请求方法'
	),
	'email' => array(
		'from' => 'noreply@terracoin.io',
		'to' => 'support@terracoin.io'
	),
	'fields' => array(
		'name' => array(
			'order' => 1,
			'type' => 'string',
			'label' => '姓名',
			'required' => true,
			'errors' => array(
				'required' => '字段\'Name\'是必需的。'
			)
		),
		'email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Email',
			'required' => true,
			'errors' => array(
				'required' => '字段\'Email\'是必需的。',
				'format' => '字段\'Email\'邮件无效。'
			)
		),
		'message' => array(
			'order' => 3,
			'type' => 'string',
			'label' => '消息',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
